### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by fattenap** [eugeneware/deglobalify#1]
Hi,

I get the following error message when I try to install via npm

npm ERR! git fetch -a origin (git://github.com/substack/esprima) error: cannot open FETCH_HEAD: Permission denied

Thanks
Frank

**Comment by eugeneware** [comment]
Hi @barcrab I couldn't replicate the issue, but I've updated all the dependences to the latest versions and republished as 0.2.0

Hope that helps.

**Comment by fattenap** [comment]
OK. I'll check it out and submit issue if I experience any problems.

Thanks
